# This file configures the analyzer, which statically analyzes Dart code to
# check for errors, warnings, and lints.
#
# The issues identified by the analyzer are surfaced in the UI of Dart-enabled
# IDEs (https://dart.dev/tools#ides-and-editors). The analyzer can also be
# invoked from the command line by running `flutter analyze`.
#
# NOTE: Native Dart 3.10.3 analyzer plugin configuration
#
# file_length_lint is configured as a native Dart 3.10.3 analyzer plugin using the
# top-level `plugins:` section. This plugin runs automatically with `flutter analyze`.
# See https://dart.dev/tools/analyzer-plugins for more information.
#
# Plugin diagnostics can be configured under the plugin's diagnostics section.
# Lint rules are disabled by default and must be explicitly enabled.

include: package:very_good_analysis/analysis_options.yaml

# Native Dart 3.10.3 analyzer plugins configuration
plugins:
  file_length_lint:
    path: custom_lints/file_length_lint
    diagnostics:
      file_too_long: true

analyzer:
  language:
    strict-casts: true
    strict-inference: true
    strict-raw-types: true
  errors:
    avoid_dynamic_calls: error
    avoid_unnecessary_containers: error
    cancel_subscriptions: error
    close_sinks: warning
    discarded_futures: error
    prefer_const_constructors: error
    prefer_const_literals_to_create_immutables: error
    prefer_final_fields: warning
    prefer_final_locals: warning
    use_build_context_synchronously: error
    use_key_in_widget_constructors: warning
    # Stricter type inference and null-safety rules
    always_declare_return_types: warning
    prefer_typing_uninitialized_variables: warning
    null_check_on_nullable_type_parameter: error
    unnecessary_nullable_for_final_variable_declarations: warning
    unnecessary_null_in_if_null_operators: warning
    avoid_null_checks_in_equality_operators: warning
    # Dart 3.10.3 new analyzer rules
    strict_top_level_inference: error
    no_wildcard_variable_uses: error
    implicit_call_tearoffs: warning
    type_literal_in_constant_pattern: error
    avoid_shadowing_type_parameters: error
    collection_methods_unrelated_type: error
    unrelated_type_equality_checks: error
    void_checks: error
  exclude:
    - build/**
    - .dart_tool/**
    - '**/.pub-cache/**'
    - ios/Pods/**
    - android/.gradle/**
    - android/app/generated/**
    - '**/*.g.dart'
    - '**/*.freezed.dart'
    - '**/*.gen.dart'
    - '**/*.gr.dart'
    - '**/*.mocks.dart'
    - '**/*.arb'
    - README.md
    # Ignore vendored packages and tooling pulled in under third_party.
    - third_party/**
    - custom_lints/**

# Keep our custom preferences on top of VGV
linter:
  rules:
    avoid_dynamic_calls: true
    always_use_package_imports: true
    prefer_single_quotes: true
    close_sinks: true
    cancel_subscriptions: true
    discarded_futures: true
    require_trailing_commas: true
    avoid_redundant_argument_values: true
    unawaited_futures: true
    use_build_context_synchronously: true
    cascade_invocations: true
    unnecessary_raw_strings: true
    avoid_multiple_declarations_per_line: true
    prefer_expression_function_bodies: true
    avoid_final_parameters: false
    prefer_const_constructors: true
    prefer_const_constructors_in_immutables: true
    prefer_const_declarations: true
    prefer_const_literals_to_create_immutables: true
    public_member_api_docs: false
    omit_local_variable_types: false
    lines_longer_than_80_chars: false
    no_default_cases: false
    unnecessary_lambdas: false
    always_put_required_named_parameters_first: true
    use_setters_to_change_properties: true
    one_member_abstracts: false
    avoid_slow_async_io: true
    only_throw_errors: true
    prefer_final_fields: true
    prefer_final_in_for_each: true
    prefer_final_locals: true
    prefer_spread_collections: true
    use_colored_box: true
    use_decorated_box: true
    use_enums: true
    use_key_in_widget_constructors: true
    use_named_constants: true
    use_string_buffers: true
    unnecessary_breaks: false
    # Stricter type inference and null-safety consistency rules
    always_declare_return_types: true
    prefer_typing_uninitialized_variables: true
    null_check_on_nullable_type_parameter: true
    unnecessary_nullable_for_final_variable_declarations: true
    unnecessary_null_in_if_null_operators: true
    avoid_null_checks_in_equality_operators: true
    prefer_if_null_operators: true
    prefer_null_aware_operators: true
    unnecessary_null_aware_assignments: true
    prefer_function_declarations_over_variables: true
    # Dart 3.10.3 new static analysis rules
    strict_top_level_inference: true
    no_wildcard_variable_uses: true
    implicit_call_tearoffs: true
    type_literal_in_constant_pattern: true
    avoid_shadowing_type_parameters: true
    avoid_types_as_parameter_names: true
    collection_methods_unrelated_type: true
    prefer_iterable_whereType: true
    unrelated_type_equality_checks: true
    void_checks: true

# Custom lint configuration
file_length_lint:
  # Default maximum number of lines allowed per file. Update as needed.
  max_lines: 260
  # Additional glob patterns to exclude beyond the built-in defaults.
  # Paths are matched against the absolute file path.
  excludes:
    - lib/generated/**

# Additional information about this file can be found at
# https://dart.dev/guides/language/analysis-options
