name: mix_lint
description: A linter for the mix package
version: 2.0.0
repository: https://github.com/btwld/mix/tree/main/packages/mix_lint

environment:
  sdk: ">=3.11.0 <4.0.0"
resolution: workspace

dependencies:
  analysis_server_plugin: ^0.3.20
  analyzer: 10.0.2
  analyzer_plugin: ^0.14.14

dev_dependencies:
  analyzer_testing: ^0.3.4
  test: ^1.31.0
  test_reflective_loader: ^0.4.0
  dart_code_metrics_presets: ^2.32.0
  flutter_lints: ^6.0.0
