#!/usr/bin/env bash
set -euo pipefail

usage() {
  cat <<'EOF'
Usage: bash tool/scaffold_feature_contract.sh --name <snake_case> [--title "Title"] [--apply]

Create the deterministic folder + feature-brief contract for a new feature.
Default mode is dry-run; it prints planned paths and writes nothing.

Options:
  --name NAME     Feature folder name, snake_case.
  --title TITLE   Human title for the generated feature brief.
  --apply         Create directories and feature brief.
  -h, --help      Show this help.
EOF
}

repo_root="$(cd "$(dirname "$0")/.." && pwd)"
name=""
title=""
apply=false

while [[ $# -gt 0 ]]; do
  case "$1" in
    --name)
      name="${2:-}"
      shift 2
      ;;
    --title)
      title="${2:-}"
      shift 2
      ;;
    --apply)
      apply=true
      shift
      ;;
    -h|--help)
      usage
      exit 0
      ;;
    *)
      echo "Unknown argument: $1" >&2
      usage >&2
      exit 2
      ;;
  esac
done

if [[ -z "$name" ]]; then
  echo "Missing required --name." >&2
  usage >&2
  exit 2
fi

if [[ ! "$name" =~ ^[a-z][a-z0-9_]*$ || "$name" == *"__"* || "$name" == *_ ]]; then
  echo "Invalid feature name: $name" >&2
  echo "Use lower snake_case, starting with a letter, with no repeated or trailing underscores." >&2
  exit 2
fi

title_from_name() {
  local value="$1"
  awk -v input="$value" 'BEGIN {
    n = split(input, parts, "_")
    for (i = 1; i <= n; i++) {
      word = toupper(substr(parts[i], 1, 1)) substr(parts[i], 2)
      output = output (i == 1 ? "" : " ") word
    }
    print output
  }'
}

if [[ -z "$title" ]]; then
  title="$(title_from_name "$name")"
fi

brief_path="docs/changes/$(date +%F)_${name}_feature_brief.md"
paths=(
  "lib/features/$name/domain"
  "lib/features/$name/data"
  "lib/features/$name/presentation/cubit"
  "lib/features/$name/presentation/pages"
  "lib/features/$name/presentation/widgets"
  "test/features/$name/domain"
  "test/features/$name/data"
  "test/features/$name/presentation"
)

cd "$repo_root"

if [[ "$apply" == false ]]; then
  echo "scaffold_feature_contract|dry-run"
  for path in "${paths[@]}"; do
    echo "plan|dir|$path"
  done
  echo "plan|file|$brief_path"
  exit 0
fi

if [[ -e "$brief_path" ]]; then
  echo "Feature brief already exists: $brief_path" >&2
  exit 1
fi

for path in "${paths[@]}"; do
  mkdir -p "$path"
  echo "created|dir|$path"
done

cat >"$brief_path" <<EOF
# Feature: $title

Generated by \`bash tool/scaffold_feature_contract.sh --name $name --apply\`.
Fill this before broad implementation. The checklist gate
\`bash tool/check_feature_brief_linked.sh\` requires a linked feature brief for
non-trivial \`lib/features/**\` changes.

## Problem

TBD

## Scope

- In: TBD
- Out: TBD

## Layers Touched

- [ ] domain
- [ ] data
- [ ] presentation
- [ ] DI
- [ ] routes / l10n

## Contracts

- Repository: TBD
- State: TBD
- DTO / mapper: TBD

## Tests

### Behaviour

- [ ] Scenario: TBD
- [ ] Files: \`test/features/$name/...\`

### State

- [ ] Scenario: loading / success / error / empty
- [ ] Files: \`test/features/$name/...\`

### Unit

- [ ] Scenario: domain or repository rule
- [ ] Files: \`test/features/$name/...\`

### Integration

- [ ] Journey: N/A unless cross-screen flow

### Proof Command

- [ ] \`flutter test test/features/$name\`

## Docs

- [ ] Update owning docs if behavior changes.

## Risks

TBD
EOF

echo "created|file|$brief_path"
