name: file_length_lint
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ">=3.11.3 <4.0.0"

dependencies:
  analysis_server_plugin: 0.3.3
  analyzer: ">=8.4.0 <9.0.0"
  meta: ^1.7.0
  yaml: 3.1.3
