name: CI

on:
  push:
    branches: [ main ]
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: "3.35.5"
          channel: stable

      - name: Flutter pub get
        run: flutter pub get

      - name: Format code
        run: dart format .

      - name: Create formatting PR
        if: github.event_name == 'push'
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          if ! git diff --quiet; then
            branch="ci/format-${GITHUB_RUN_ID}"
            git config user.name "github-actions[bot]"
            git config user.email "github-actions[bot]@users.noreply.github.com"
            git checkout -b "$branch"
            git add .
            git commit -m "chore: apply dart format"
            git push origin "$branch"
            gh pr create --repo "$GITHUB_REPOSITORY" --head "$branch" \
              --title "chore: apply dart format" \
              --body "Automated formatting updates from CI." || true
          fi

      - name: Flutter analyze
        run: flutter analyze

      - name: Flutter tests (with coverage)
        run: flutter test --coverage

      - name: Enforce coverage threshold
        run: |
          COVERAGE_FILE=coverage/lcov.info
          TARGET=60
          ACTUAL=$(lcov --summary "$COVERAGE_FILE" | awk '/lines/ {print $2}' | sed 's/%//')
          echo "Coverage: $ACTUAL%"
          awk -v actual="$ACTUAL" -v target="$TARGET" 'BEGIN { exit (actual + 0 >= target + 0 ? 0 : 1) }'

      - name: Upload coverage report
        uses: actions/upload-artifact@v4
        with:
          name: coverage-lcov
          path: coverage/lcov.info
