name: OSV-Scanner PR Scan

on:
  pull_request:
    branches: [main, master]
  merge_group:
    branches: [main, master]

permissions:
  actions: read
  security-events: write
  contents: read

env:
  FORCE_JAVASCRIPT_ACTIONS_TO_NODE24: true

jobs:
  scan-pr:
    uses: google/osv-scanner-action/.github/workflows/osv-scanner-reusable-pr.yml@v2.5.1
    with:
      scan-args: |-
        --lockfile=pubspec.lock
